### ISSUE TITLE
Add density evaluation?

### ISSUE THREAD

**Issue by ocramz** [jtobin/mwc-probability#11]
It would be handy if `Prob` had an additional field with a function to evaluate the associated PDF. `statistics` uses typeclasses for this. 

I can contribute a lightweight, native (but approximate) implementation of the Gamma function, which makes it possible to compute a number of continuous distributions.

What do you think @jtobin ?

**Comment by jtobin** [comment]
Hmm.  As I am predisposed to the unix-style "do one thing and do it well" philosophy, I am inclined to avoid it. 😁  When I grab this library I do so because I want a probability monad wrapper for the MWC PRNG -- not because I want to compute probabilities.  It seems that another library would be better for the latter case (I usually roll my own densities, or if I'm lazy just use the ones in `statistics`).

`statistics` is pretty heavyweight, but this library (via `mwc-random`, which depends on `vector`) is comparably heavy if one is just looking to compute probabilities.  Perhaps there's room for a new library?
