### ISSUE TITLE
Too sparse documentation ?

### ISSUE THREAD

**Issue by ocramz** [jtobin/mwc-probability#14]
Hi @jtobin , why did you delete most of the docs I wrote?

I don't think it was wasted space, and generally I lean towards being more generous with explanations, haddock structure, and introductory stuff. Would love to know your thoughts on this.

**Comment by jtobin** [comment]
Hey Marco, I was just bumping the Stackage versions last night and decided to clean up the docs.  I didn't have much in mind when I did it -- just tried to streamline everything and keep the style consistent.  In the end I guess the result was just to continue giving short descriptions of everything, with examples where particularly useful & adding comments on legal parameter values.

I just checked to see what docs of yours I might have inadvertently slashed, but as far as I can tell it was really only the small note at the start (re: running the examples, plus the reference to Devroye) and the list of distributions in the README, yeah?

For the examples, I think there are sufficient references to using the `mwc-random` PRNG (e.g. `create >>= sample uniform`, `gen <- createSystemRandom; sample uniform gen`) such that there doesn't need to be a special section on it at the start of the docs.  Additionally the relevant docs from `mwc-random` themselves are already included in the generated Haddocks, so there is ample material on using the underlying PRNG.

The Devroye reference I just axed because I don't think it's necessary to include.  My rationale is that the user doesn't need to be concerned with *how* variates are sampled, precisely (e.g. by rejection sampling or whatever other method) -- just that they are sampled correctly.

The only other significant thing I think I axed was the list of supported distributions in the README, I guess?  I don't think it's necessary to include them there -- they are already listed in more detail in the generated Haddocks, which are automatically kept up to date with the code.  With the README one has to make sure that its contents don't get out of sync with the actual codebase, and just strikes me as an added hassle, without much (if any) benefit.  I did add a comment to the README to reference the Hackage docs, IIRC.

So as far as I can tell, I didn't axe anything substantial (certainly none of it struck me as substantial at the time).  Was I way off?

**Comment by ocramz** [comment]
Sure, nothing major and no hurt feelings. The README doesn't stay in sync that's true; perhaps I'll just hyperlink a few meaningful functions in a later version.

However I think mentioning our references is important for reproducibility, in particular since we don't provide distribution tests or other straightforward ways of showing correctness (let alone proofs).
